Fix Step1X multi-image handling by concatenating images
- Step1X pipeline doesn't support list of images
- Concatenate multiple images horizontally before passing to pipeline
- Allows model to see both people in WinoBias experiment
- Fixes AttributeError: 'list' object has no attribute 'size'